export const NOTICED_ADDING_SIGNAL_MSG_TRUE = "NOTICED_ADDING_SIGNAL_MSG_TRUE";
export const NOTICED_ADDING_SIGNAL_MSG_FALSE = "NOTICED_ADDING_SIGNAL_MSG_FALSE";
export const NOTICED_ADDED_SIGNAL_MSG_TRUE = "NOTICED_ADDED_SIGNAL_MSG_TRUE";
export const NOTICED_ADDED_SIGNAL_MSG_FALSE = "NOTICED_ADDED_SIGNAL_MSG_FALSE";
export const NOTICED_FAIL_ADDED_SIGNAL_MSG_TRUE = "NOTICED_FAIL_ADDED_SIGNAL_MSG_TRUE";
export const NOTICED_FAIL_ADDED_SIGNAL_MSG_FALSE = "NOTICED_FAIL_ADDED_SIGNAL_MSG_FALSE";
