export const SET_SEARCHED_POKEMONS = "SET_SEARCHED_POKEMONS";
export const SET_SEARCHED_QUERY = "SET_SEARCHED_QUERY";
export const SET_SEARCHED_TYPE = "SET_SEARCHED_TYPE";
export const RESET_SEARCHED_PARAMS = "RESET_SEARCHED_PARAMS";
export const RESET_SEARCHED_POKEMONS = "RESET_SEARCHED_POKEMONS";
export const REMOVE_SEARCHED_PARAMS_TYPE = "REMOVE_SEARCHED_PARAMS_TYPE";
